import { OurWorksPageConfig } from "@/types";

const config: OurWorksPageConfig = {
   heading: "Our Works",
   default_category: "Category 1",
   image_categories: [
      {
         name: "Category 1",
         images: [
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
      {
         name: "Category 2",
         images: [
            "/assets/something.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/dummy.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
      {
         name: "Category 3",
         images: [
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
   ],
   video_category: "Videos",
   videos: [
      "OGy_0tzRwPQ",
      "OGy_0tzRwPQ",
      "QAumQUsqwtw",
      "nvpWVVKFwl8",
      "WqrI-pZPE9s",
      "PUZ-d7QE3X8",
      "UQ4xmxFVlVw",
      "s3y8AYcMkXw",
      "NIkqJZyVfYI",
      "5Z1vl4DgHXY",
      "A0sVt42gS44",
   ],
};

export default config;
