import { OurWorksPageConfig } from "@/types";

const config: OurWorksPageConfig = {
   heading: "Our Works",
   default_category: "Category 1",
   image_categories: [
      {
         name: "Ring Ceremony",
         images: [
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
      {
         name: "Haldi",
         images: [
            "/assets/h1.webp",
            "/assets/h2.webp",
            "/assets/h3.webp",
            "/assets/h4.webp",
            "/assets/h5.webp",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
      {
         name: "Mehndi",
         images: [
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
      {
         name: "Wedding",
         images: [
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
      {
         name: "Pre-Wedding",
         images: [
            "/assets/our work/pre wed/a (1).webp",
            "/assets/our work/pre wed/a (2).webp",
            "/assets/our work/pre wed/a (3).webp",
            "/assets/our work/pre wed/a (4).webp",
            "/assets/our work/pre wed/a (5).webp",
            "/assets/our work/pre wed/a (6).webp",
            "/assets/our work/pre wed/a (7).webp",
            "/assets/our work/pre wed/a (8).webp",
            "/assets/our work/pre wed/a (9).webp",
            "/assets/our work/pre wed/a (10).webp",
            "/assets/our work/pre wed/a (1).webp",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
            "/assets/dummy.jpg",
            "/assets/something.jpg",
         ],
      },
   ],
   video_category: "Videos",
   videos: [
      "OGy_0tzRwPQ",
      "OGy_0tzRwPQ",
      "QAumQUsqwtw",
      "nvpWVVKFwl8",
      "WqrI-pZPE9s",
      "PUZ-d7QE3X8",
      "UQ4xmxFVlVw",
      "s3y8AYcMkXw",
      "NIkqJZyVfYI",
      "5Z1vl4DgHXY",
      "A0sVt42gS44",
   ],
};

export default config;
